alias lah='ls -lah'
alias reload='clear && source $BASHRC'
alias ducks='sudo du -ah --max-depth=1 | sort -hr | head -n 11'
alias cd..='cd ..' # Gets rid of command not found
alias edit='nvim $BASHRC'
alias apt-update='sudo apt-get update && sudo apt-get upgrade && sudo apt autoremove'
alias ⸸='sudo shutdown now'
alias reboot='sudo systemctl reboot'
alias vim='$HOME/.dotfiles/.memes/activate-vim.sh'
alias uefi='systemctl reboot --firmware-setup'
alias shutdown='sudo systemctl poweroff'
