shell /bin/bash -l

initial_window_width 80
initial_window_height 36

font_family      Iosevka Regular
bold_font        Iosevka Bold
italic_font      Iosevka Italic
bold_italic_font Iosevka Bold Italic

font_size   18.0

allow_remote_control yes

background_opacity 0.6

include colors.conf
