#!/usr/bin/env bash

BATTERY_PATH="/sys/class/power_supply/BAT0/capacity"

# Prevent desktop errors
if [[ -f "$BATTERY_PATH" ]];then
	PERCENTAGE=$(cat "$BATTERY_PATH")
fi

# Set to 100 if device doesnt have battery
PERCENTAGE=${PERCENTAGE:="100"}

echo "$PERCENTAGE" | awk '{
    if ($1 > 80)       state = " ";
    else if ($1 > 60)  state = " ";
    else if ($1 > 40)  state = " ";
    else if ($1 > 20)  state = " ";
    else               state = " ";
    printf "%s %s%%", state, $1;
}'

