#!/usr/bin/env bash

# Get the first Ethernet interface
interface=$(ip -o link show | awk -F': ' '$2 ~ /^e/ && $0 ~ /state UP/ {print $2; exit}')

# Read RX/TX data
read rx1 tx1 < <(awk -v iface="$interface" '$1 ~ iface ":" {print $2, $10}' /proc/net/dev)

sleep 1

# Read updated RX/TX data
read rx2 tx2 < <(awk -v iface="$interface" '$1 ~ iface ":" {print $2, $10}' /proc/net/dev)

# Calculate download/upload in Kb
DOWNLOAD=$(( ((rx2 - rx1) * 8) / 1024 ))
UPLOAD=$(( ((tx2 - tx1) * 8) / 1024 ))

# Print the result
printf "%s Kb  | %s Kb  |\n" "$DOWNLOAD" "$UPLOAD"
