# Start Hyprland
if [[ -z "$DISPLAY" ]] && [[ "$(tty)" == "/dev/tty1" ]];then
	export $XDG_SESSION_TYPE=wayland
	dbus-run-session Hyprland
fi

# Load Custom exports and paths
if [[ -d "$HOME/.exports" ]]; then
	for file in "$HOME/.exports/"*; do
		if [[ -f "$file" ]]; then
			source "$file"
		fi
	done
fi

# Source prompt config
source "$XDG_CONFIG_HOME/bash/prompt"

# Load custom aliases if available
source "$XDG_CONFIG_HOME/bash/aliases"

# Load custom bash functions
source "$XDG_CONFIG_HOME/bash/functions"

# Enable Bash autocompletion support
source "$XDG_CONFIG_HOME/bash/completion"

