# Start Sway 
if [[ -z "$DISPLAY" ]] && [[ "$(tty)" == "/dev/tty1" ]]; then
	export XDG_SESSION_TYPE="wayland"
	export MOZ_ENABLE_WAYLAND=1 
	exec sway 
fi

# Source env variables
source "$XDG_CONFIG_HOME/bash/env-exports"

# Source prompt config
source "$XDG_CONFIG_HOME/bash/prompt"

# Load custom aliases if available
source "$XDG_CONFIG_HOME/bash/aliases"

# Load custom bash functions
source "$XDG_CONFIG_HOME/bash/functions"

# Load custom bash history settings
source "$XDG_CONFIG_HOME/bash/history"

# Enable Bash autocompletion support
source "$XDG_CONFIG_HOME/bash/completion"

