#!/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
PREFIX=$(echo "$BRANCH_NAME" | grep -oE '[a-zA-Z]+-[0-9]+')
COMMIT_MSG_FILE="$1"

if [ -n "$PREFIX" ]; then
  BODY=$(grep -v '^#' "$COMMIT_MSG_FILE")
  COMMENTS=$(grep '^#' "$COMMIT_MSG_FILE")
  {
    echo "$PREFIX $BODY"
    echo "$COMMENTS"
  } > "$COMMIT_MSG_FILE"
fi

