#!/usr/bin/env bash
set -euo pipefail

GIT_PROJECTS_DIR="${SRC:-$HOME/src}"
GIT_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/git"

mkdir -p "$GIT_CONFIG_DIR" "$GIT_PROJECTS_DIR"

cat > "$GIT_CONFIG_DIR/config" <<EOF
[user]
    name = Tomáš Bosák
    email = tombos255@gmail.com

[core]
    editor = nvim

[includeIf "gitdir:${GIT_PROJECTS_DIR}/handel/"]
    path = ${GIT_CONFIG_DIR}/handel.gitconfig

[includeIf "gitdir:${GIT_PROJECTS_DIR}/github/"]
    path = ${GIT_CONFIG_DIR}/github.gitconfig

[alias]
    exclude = "!f() { for f in \"\$@\"; do echo \"\$f\" >> .git/info/exclude; done; }; f"
EOF

